Branch table feature
AY2324S1-CS2103T-W13-2/tp pull request #99
Opened 2023-10-21 03:45 UTC by LINCHENYU2030S

add table command

2023-10-21 14:05 UTC, ChuanXinNg requested changes
LGTM. Can be merged after some modification. I don't really get why is type long used for the counts, I think int is enough to hold the counts🤔.

2023-10-21 14:13 UTC, LINCHENYU2030S commented on src/main/java/seedu/address/logic/commands/GenderTableCommandResult.java
> +    private Long femaleCount;
This is actually the return type of java stream count() method and the Long data type for table count is only used in table-related stuff.

2023-10-21 14:17 UTC, LINCHENYU2030S commented on src/main/java/seedu/address/logic/commands/GenderTableCommandResult.java
> +    private static final String feedbackToUserMessage = "A table categorized by gender is shown";
Thanks for pointing it out!

2023-10-21 14:24 UTC, LINCHENYU2030S commented on src/main/java/seedu/address/logic/commands/TableCommand.java
> +        case "g/":
Thanks for pointing out! I just notice prefix has instance method getPrefix() which will return me the corresponding prefix in String.

2023-10-21 14:37 UTC, LINCHENYU2030S commented on src/main/java/seedu/address/logic/commands/TableCommand.java
> +        String[] titles = new String[] {"Sec 1", "Sec 2", "Sec 3", "Sec 4"};
Noted with thanks!

2023-10-21 14:44 UTC, LINCHENYU2030S commented on src/main/java/seedu/address/logic/commands/GenderTableCommandResult.java
> +    private Long femaleCount;
I think we may leave it as Long first, and we can change it if it is not good to fit in later implementation.

2023-10-21 15:02 UTC, LINCHENYU2030S commented on src/main/java/seedu/address/logic/commands/GenderTableCommandResult.java
> +    private Long femaleCount;
just find out that java steam has mapToInt method which I can used to convert Long to Int in just one to two lines, will update now

2023-10-22 08:52 UTC, ChuanXinNg approved these changes
LGTM. Modifications on the previous comments are made and good job for adding use cases.

2023-10-22 08:52 UTC, merged